###############################################################################
## SPORTS2D PROJECT PARAMETERS                                               ##
###############################################################################

# Configure your project parameters here


[project]
video_dir = '' # BETWEEN SINGLE QUOTES! # If empty, project dir is current dir
video_file = 'demo.mp4'
frame_rate = 30 #Hz


[pose]
pose_algo = 'BLAZEPOSE' # 'OPENPOSE' or 'BLAZEPOSE' 
# OpenPose is more accurate and supports multi-person detection, but needs to be installed separately	
# Coming soon: 'deeplabcut', 'alphapose'
	
	[pose.BLAZEPOSE]
	# 0,1,2. 2 is slightly slower but more accurate
	model_complexity = 2 
		
	[pose.OPENPOSE]
	# Install OpenPose from https://github.com/CMU-Perceptual-Computing-Lab/openpose
	#BODY_25 is standard, BODY_25B is more accurate but requires downloading the model from 
	# https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/blob/master/experimental_models/README.md
	openpose_model = 'BODY_25' 
	# Installation path of openpose (between single quotes) 
	openpose_path = 'D:\softs\openpose-1.6.0-binaries-win64-gpu-flir-3d_recommended\openpose' 	
	

[compute_angles]
joint_angles = ['rankle', 'lankle', 'rknee', 'lknee', 'rhip', 'lhip', 'rshoulder', 'lshoulder', 'relbow', 'lelbow']
# select among ['rankle', 'lankle', 'rknee', 'lknee', 'rhip', 'lhip', 'rshoulder', 'lshoulder', 'relbow', 'lelbow']
segment_angles = ['rfoot', 'lfoot', 'rshank', 'lshank', 'rthigh', 'lthigh', 'trunk', 'rarm', 'larm', 'rforearm', 'lforearm']
# select among ['rfoot', 'lfoot', 'rshank', 'lshank', 'rthigh', 'lthigh', 'trunk', 'rarm', 'larm', 'rforearm', 'lforearm']
   	
	

# ADVANCED CONFIGURATION
	
[pose_advanced] # only for OPENPOSE
load_pose = true # else proceed to detection
save_vid = true
save_img = true
interp_gap_smaller_than = 5 # do not interpolate bigger gaps
show_plots = false
filter = true
filter_type = 'butterworth' # butterworth, gaussian, LOESS, median
   [pose_advanced.butterworth]
   order = 4 
   cut_off_frequency = 6 # Hz
   [pose_advanced.gaussian]
   sigma_kernel = 1 #px
   [pose_advanced.loess]
   nb_values_used = 5 # = fraction of data used * nb frames
   [pose_advanced.median]
   kernel_size = 3


[compute_angles_advanced] # for OPENPOSE and BLAZEPOSE
show_plots = false
filter = true
filter_type = 'butterworth' # butterworth, gaussian, LOESS, median
   [compute_angles_advanced.butterworth]
   order = 4 
   cut_off_frequency = 6 # Hz
   [compute_angles_advanced.gaussian]
   sigma_kernel = 1 #px
   [compute_angles_advanced.loess]
   nb_values_used = 5 # = fraction of data used * nb frames
   [compute_angles_advanced.median]
   kernel_size = 3